apiVersion: apps/v1
kind: Deployment

metadata:
  name: abc-website-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: abc-website

  template:
    metadata:
      labels:
        app: abc-website

    spec:
      containers:
      - name: abc-website-container
        image: abc-technologies
        imagePullPolicy: Never
        ports:
        - containerPort: 80